export const FETCH_USERS = "FETCH_USERS";

export const FETCH_POSTS = "FETCH_POSTS";
export const CREATE_POST = "CREATE_POST";

export const FETCH_TEMPERATURE = "FETCH_TEMPERATURE";

export const FETCH_LOADING = "FETCH_LOADING";
export const FETCH_LOADED = "FETCH_LOADED";
